

__MBN_INPUT_LIST_BUTTON_KEYBOARD = array_create(20, undefined);
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT = array_create(20, undefined);

__MBN_INPUT_LIST_BUTTON_GAMEPAD = array_create(20, undefined);
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT = array_create(20, undefined);



__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.UP]		= [ ord("W"), vk_up    ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.DOWN]	= [ ord("S"), vk_down  ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.LEFT]	= [ ord("A"), vk_left  ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.RIGHT]	= [ ord("D"), vk_right ];

__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.FUNC0]	= [ ord("J"), ord("Z"), ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.FUNC1]	= [ ord("K"), ord("X") ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.FUNC2]	= [ vk_space, vk_shift ];
__MBN_INPUT_LIST_BUTTON_KEYBOARD_DEFAULT[INPUT.FUNC3]	= [ vk_escape ];



__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.UP]		= [ gp_padu ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.DOWN]		= [ gp_padd ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.LEFT]		= [ gp_padl ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.RIGHT]	= [ gp_padr ];

__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.FUNC0]	= [ gp_face1 ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.FUNC1]	= [ gp_face2 ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.FUNC2]	= [ gp_face3 ];
__MBN_INPUT_LIST_BUTTON_GAMEPAD_DEFAULT[INPUT.FUNC3]	= [ gp_face4 ];



