/// @description Insert description here
// You can write your code in this editor

INGAME_CAMERA_X_TARGET = clamp(INGAME_CAMERA_X_TARGET,
0, room_width - 0);
INGAME_CAMERA_Y_TARGET = clamp(INGAME_CAMERA_Y_TARGET,
0, room_height - 0);

INGAME_CAMERA_X = Lerp(INGAME_CAMERA_X, INGAME_CAMERA_X_TARGET, 0.16);
INGAME_CAMERA_Y = Lerp(INGAME_CAMERA_Y, INGAME_CAMERA_Y_TARGET, 0.16);
	
INGAME_CAMERA_X_LEFT = INGAME_CAMERA_X - INGAME_WIDTH  / 2;
INGAME_CAMERA_Y_TOP  = INGAME_CAMERA_Y - INGAME_HEIGHT / 2;

INGAME_CAMERA_SHAKE[1] = Lerp(INGAME_CAMERA_SHAKE[1], 0, 0.1, 0.25);


